apply plugin: 'com.android.application'

android {
    compileSdk 35
    namespace 'org.kanaha.audio'

    defaultConfig {
        applicationId "org.kanaha.audio"
        minSdkVersion 28
        targetSdkVersion 35
        versionCode 1
        versionName "1.0.0"

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt')
        }
    }

    lint {
        abortOnError false
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE',
                         'META-INF/NOTICE', 'META-INF/*.kotlin_module']
        }
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
}
